### ISSUE TITLE
name 'get_model_name_from_path' is not defined

### ISSUE THREAD

**Issue by jby20180901** [EvolvingLMMs-Lab/lmms-eval#214]
2024-08-27 16:25:35.109 | ERROR    | __main__:cli_evaluate:216 - Error during evaluation: name 'get_model_name_from_path' is not defined
Traceback (most recent call last):
  File "/home/jiangbaoyang/lmms-eval-main/lmms_eval/__main__.py", line 202, in cli_evaluate
    results, samples = cli_evaluate_single(args)
  File "/home/jiangbaoyang/lmms-eval-main/lmms_eval/__main__.py", line 298, in cli_evaluate_single
    results = evaluator.simple_evaluate(
  File "/home/jiangbaoyang/lmms-eval-main/lmms_eval/utils.py", line 434, in _wrapper
    return fn(*args, **kwargs)
  File "/home/jiangbaoyang/lmms-eval-main/lmms_eval/evaluator.py", line 96, in simple_evaluate
    lm = lmms_eval.api.registry.get_model(model).create_from_arg_string(
  File "/home/jiangbaoyang/lmms-eval-main/lmms_eval/api/model.py", line 92, in create_from_arg_string
    return cls(**args, **args2)
  File "/home/jiangbaoyang/lmms-eval-main/lmms_eval/models/llava.py", line 92, in __init__
    model_name = model_name if model_name is not None else get_model_name_from_path(pretrained)
NameError: name 'get_model_name_from_path' is not defined
[rank0]:[W827 16:25:35.425639337 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
这是为什么呢

**Comment by BrenchCC** [comment]
可以看看你的命令行输入吗，从报错内容看就是你的模型路径出问题，也许是模型名字问题

**Comment by Bleking** [comment]
Hello, I recently had the same error. I do not know your command line but what I can tell you is that you have to use the directory of the model from https://huggingface.co/lmms-lab.

For example, "--model_args pretrained lmms-lab/llava-onevision-qwen2-0.5b-si".

I hope it helped you.

**Comment by Raibows** [comment]
I had the same issue when I'm trying to use the example command listed in the README

```
python3 -m accelerate.commands.launch \
    --num_processes=8 \
    -m lmms_eval \
    --model llava \
    --model_args pretrained="liuhaotian/llava-v1.5-7b" \
    --tasks mme,mmbench_en \
    --batch_size 1 \
    --log_samples \
    --log_samples_suffix llava_v1.5_mme_mmbenchen \
    --output_path ./logs/
```

**Comment by jerife** [comment]
You should clone the run LLaVA-NEXT repo and run script in LLaVA-NEXT folder.
Check here: https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/main/docs/run_examples.md#llava
