### ISSUE TITLE
I cannot use lmms-eval to evaluate Videoxl

### ISSUE THREAD

**Issue by SplendidYuan** [EvolvingLMMs-Lab/lmms-eval#448]
```
Traceback (most recent call last):
File "/home/shengy/miniconda3/envs/videoxl/lib/python3.10/site-packages/lmms_eval/main.py", line 329, in cli_evaluate
results, samples = cli_evaluate_single(args)
File "/home/shengy/miniconda3/envs/videoxl/lib/python3.10/site-packages/lmms_eval/main.py", line 470, in cli_evaluate_single
results = evaluator.simple_evaluate(
File "/home/shengy/miniconda3/envs/videoxl/lib/python3.10/site-packages/lmms_eval/utils.py", line 533, in _wrapper
return fn(*args, **kwargs)
File "/home/shengy/miniconda3/envs/videoxl/lib/python3.10/site-packages/lmms_eval/evaluator.py", line 169, in simple_evaluate
lm = ModelClass.create_from_arg_string(
File "/home/shengy/miniconda3/envs/videoxl/lib/python3.10/site-packages/lmms_eval/api/model.py", line 110, in create_from_arg_string
return cls(**args, **args2)
TypeError: Can't instantiate abstract class Videoxl with abstract method generate_until_multi_round

2024-11-29 16:05:34.047 | ERROR | main:cli_evaluate:348 - Error during evaluation: Can't instantiate abstract class Videoxl with abstract method generate_until_multi_round. Please set --verbosity=DEBUG to get more information.
```
I don't know what specific modifications are needed.Could you please tell us the solution? Thank you very much

**Comment by pufanyi** [comment]
Hi, it seems that it is because you need to add an empty method `generate_until_multi_round` in your model if your model does not support multi-round evaluation, like:

https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/d900496af837dcf5afe3d9efea471d624fd20588/lmms_eval/models/llava_vid.py#L528-L529

**Comment by SplendidYuan** [comment]
### That's great. I can't thank you enough👍😘

> Hi, it seems that it is because you need to add an empty method `generate_until_multi_round` in your model if your model does not support multi-round evaluation, like:
> 
> https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/d900496af837dcf5afe3d9efea471d624fd20588/lmms_eval/models/llava_vid.py#L528-L529
