### ISSUE TITLE
An issue during evaluating MathVista

### ISSUE THREAD

**Issue by simplelifetime** [EvolvingLMMs-Lab/lmms-eval#75]
I don't know how to solve it, seem to be a problem with huggingface evaluate module.
Traceback (most recent call last):
  File "/home/aka/anaconda3/envs/lmms/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/akaanaconda3/envs/lmms/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aka/lmms-eval/lmms_eval/__main__.py", line 24, in <module>
    from lmms_eval import evaluator, utils
  File "/home/aka/lmms-eval/lmms_eval/evaluator.py", line 17, in <module>
    import lmms_eval.api.metrics
  File "/home/aka/lmms-eval/lmms_eval/api/metrics.py", line 146, in <module>
    exact_match = evaluate.load("exact_match")
  File "/home/aka/anaconda3/envs/lmms/lib/python3.10/site-packages/evaluate/loading.py", line 751, in load
    evaluation_cls = import_main_class(evaluation_module.module_path)
  File "/home/aka/anaconda3/envs/lmms/lib/python3.10/site-packages/evaluate/loading.py", line 76, in import_main_class
    module = importlib.import_module(module_path)
  File "/home/aka/anaconda3/envs/lmms/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/aka/.cache/huggingface/modules/evaluate_modules/metrics/evaluate-metric--exact_match/009c8b5313309ea5b135d526433d5ee76508ba1554cbe88310a30f85bb57ec88/exact_match.py", line 16
    }
    ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' on line 14
E0507 14:41:36.009469 139918226703296 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 36925) of binary: /home/aka/anaconda3/envs/lmms/bin/python

**Comment by baichuanzhou** [comment]
You should replace the `exact_match.py` file with this [file](https://github.com/huggingface/evaluate/blob/main/metrics/exact_match/exact_match.py). I encountered the same issue today. It seems to be a problem from hf-mirror.
